language: rust

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

env:
  - CXX=g++-5

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
